In [1]:
#importar as bibliotecas 
from numpy import pi
from numpy import sys
from numpy import newaxis
import numpy as np

In [2]:
print('Versão atual do numpy', np.__version__)

Versão atual do numpy 1.18.5


In [3]:
rg = np.random.default_rng(1)
a = np.floor(10 * rg.random((2, 12)))
a

array([[5., 9., 1., 9., 3., 4., 8., 4., 5., 0., 7., 5.],
       [3., 7., 3., 4., 1., 4., 2., 2., 7., 2., 4., 9.]])

In [4]:
#Divide a matriz 'a' em 3
np.hsplit(a, 3)

[array([[5., 9., 1., 9.],
        [3., 7., 3., 4.]]),
 array([[3., 4., 8., 4.],
        [1., 4., 2., 2.]]),
 array([[5., 0., 7., 5.],
        [7., 2., 4., 9.]])]

In [5]:
#Divide 'a' após a terceira e a quarta coluna 
np.hsplit(a,(3, 4))

[array([[5., 9., 1.],
        [3., 7., 3.]]),
 array([[9.],
        [4.]]),
 array([[3., 4., 8., 4., 5., 0., 7., 5.],
        [1., 4., 2., 2., 7., 2., 4., 9.]])]